//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO23_GUI_idea.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TicketModel", Namespace="http://schemas.datacontract.org/2004/07/BKM00720Service")]
    [System.SerializableAttribute()]
    public partial class TicketModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet dsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet ds {
            get {
                return this.dsField;
            }
            set {
                if ((object.ReferenceEquals(this.dsField, value) != true)) {
                    this.dsField = value;
                    this.RaisePropertyChanged("ds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchModel", Namespace="http://schemas.datacontract.org/2004/07/BKM00720Service")]
    [System.SerializableAttribute()]
    public partial class SearchModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet dsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet ds {
            get {
                return this.dsField;
            }
            set {
                if ((object.ReferenceEquals(this.dsField, value) != true)) {
                    this.dsField = value;
                    this.RaisePropertyChanged("ds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultModel", Namespace="http://schemas.datacontract.org/2004/07/BKM00720Service")]
    [System.SerializableAttribute()]
    public partial class ResultModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BasketCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BasketCode {
            get {
                return this.BasketCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BasketCodeField, value) != true)) {
                    this.BasketCodeField = value;
                    this.RaisePropertyChanged("BasketCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocNumber {
            get {
                return this.DocNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DocNumberField, value) != true)) {
                    this.DocNumberField = value;
                    this.RaisePropertyChanged("DocNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgCode {
            get {
                return this.OrgCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgCodeField, value) != true)) {
                    this.OrgCodeField = value;
                    this.RaisePropertyChanged("OrgCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TicketNo {
            get {
                return this.TicketNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketNoField, value) != true)) {
                    this.TicketNoField = value;
                    this.RaisePropertyChanged("TicketNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.BKM00720Service")]
    public interface BKM00720Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BKM00720Service/Truck_Validate", ReplyAction="http://tempuri.org/BKM00720Service/Truck_ValidateResponse")]
        string Truck_Validate(string LicensePlate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BKM00720Service/GetTicketLst", ReplyAction="http://tempuri.org/BKM00720Service/GetTicketLstResponse")]
        BO23_GUI_idea.ServiceReference1.TicketModel GetTicketLst(string OrgCode, string LicensePlate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BKM00720Service/Search", ReplyAction="http://tempuri.org/BKM00720Service/SearchResponse")]
        BO23_GUI_idea.ServiceReference1.SearchModel Search(string OrgCode, string LicensePlate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BKM00720Service/AddTicket", ReplyAction="http://tempuri.org/BKM00720Service/AddTicketResponse")]
        string AddTicket(BO23_GUI_idea.ServiceReference1.ResultModel item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BKM00720ServiceChannel : BO23_GUI_idea.ServiceReference1.BKM00720Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BKM00720ServiceClient : System.ServiceModel.ClientBase<BO23_GUI_idea.ServiceReference1.BKM00720Service>, BO23_GUI_idea.ServiceReference1.BKM00720Service {
        
        public BKM00720ServiceClient() {
        }
        
        public BKM00720ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BKM00720ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BKM00720ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BKM00720ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Truck_Validate(string LicensePlate) {
            return base.Channel.Truck_Validate(LicensePlate);
        }
        
        public BO23_GUI_idea.ServiceReference1.TicketModel GetTicketLst(string OrgCode, string LicensePlate) {
            return base.Channel.GetTicketLst(OrgCode, LicensePlate);
        }
        
        public BO23_GUI_idea.ServiceReference1.SearchModel Search(string OrgCode, string LicensePlate) {
            return base.Channel.Search(OrgCode, LicensePlate);
        }
        
        public string AddTicket(BO23_GUI_idea.ServiceReference1.ResultModel item) {
            return base.Channel.AddTicket(item);
        }
    }
}
