//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO23_GUI_idea.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BO23_GUI_idea.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please activate card....
        /// </summary>
        internal static string enActiveCard {
            get {
                return ResourceManager.GetString("enActiveCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string enCancel {
            get {
                return ResourceManager.GetString("enCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string enOK {
            get {
                return ResourceManager.GetString("enOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string enStart {
            get {
                return ResourceManager.GetString("enStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B048.
        /// </summary>
        internal static string SriThaiCode {
            get {
                return ResourceManager.GetString("SriThaiCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีค้าง.
        /// </summary>
        internal static string TellNotRemaining {
            get {
                return ResourceManager.GetString("TellNotRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีค้างส่ง.
        /// </summary>
        internal static string TellRemaining {
            get {
                return ResourceManager.GetString("TellRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิก.
        /// </summary>
        internal static string thCancel {
            get {
                return ResourceManager.GetString("thCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรอกทะเบียนรถ.
        /// </summary>
        internal static string thFillCarTag {
            get {
                return ResourceManager.GetString("thFillCarTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตกลง.
        /// </summary>
        internal static string thOK {
            get {
                return ResourceManager.GetString("thOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาแตะบัตร....
        /// </summary>
        internal static string thPresentCard {
            get {
                return ResourceManager.GetString("thPresentCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำลังค้นหาข้อมูล....
        /// </summary>
        internal static string thSearching {
            get {
                return ResourceManager.GetString("thSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เข้าระบบ.
        /// </summary>
        internal static string thStart {
            get {
                return ResourceManager.GetString("thStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำลังตรวจสอบระบบ....
        /// </summary>
        internal static string thValidateSystem {
            get {
                return ResourceManager.GetString("thValidateSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณารอสักครู่.
        /// </summary>
        internal static string thWait {
            get {
                return ResourceManager.GetString("thWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B041.
        /// </summary>
        internal static string TwoToneCode {
            get {
                return ResourceManager.GetString("TwoToneCode", resourceCulture);
            }
        }
    }
}
